% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\author{}
\date{\vspace{-2.5em}}

\begin{document}

\newpage
\tableofcontents 
\newpage
\listoftables 
\newpage
\listoffigures 
\newpage

\section{Rationale and Research
Questions}\label{rationale-and-research-questions}

This project explores the relationship between air quality and social
vulnerability in California.

Research Question: Do communities facing higher pollution levels have
less access to health insurance and medical care?

\newpage

\section{Dataset Information}\label{dataset-information}

\section{Dataset Information}\label{dataset-information-1}

\section{Source and Content of Data}\label{source-and-content-of-data}

\section{The data used in this analysis was obtained from two main
sources:}\label{the-data-used-in-this-analysis-was-obtained-from-two-main-sources}

\section{the Environmental Protection Agency (EPA) for PM2.5
concentration
data,}\label{the-environmental-protection-agency-epa-for-pm2.5-concentration-data}

\section{and the Centers for Disease Control and Prevention (CDC) for
the Social Vulnerability Index (SVI)
data.}\label{and-the-centers-for-disease-control-and-prevention-cdc-for-the-social-vulnerability-index-svi-data.}

\section{The PM2.5 concentration data was collected for the years 2000
and
2022.}\label{the-pm2.5-concentration-data-was-collected-for-the-years-2000-and-2022.}

\section{This dataset contains the daily mean PM2.5 levels measured in
micrograms per cubic meter
(μg/m3)}\label{this-dataset-contains-the-daily-mean-pm2.5-levels-measured-in-micrograms-per-cubic-meter-ux3bcgm3}

\section{for each county in California. The data was aggregated to
calculate the yearly average
PM2.5}\label{for-each-county-in-california.-the-data-was-aggregated-to-calculate-the-yearly-average-pm2.5}

\section{concentration for each
county.}\label{concentration-for-each-county.}

\section{The SVI data provides information on the social vulnerability
of California
counties}\label{the-svi-data-provides-information-on-the-social-vulnerability-of-california-counties}

\section{across several socioeconomic indicators. The specific variables
used in this analysis
include:}\label{across-several-socioeconomic-indicators.-the-specific-variables-used-in-this-analysis-include}

\section{- Percent of population below 150\% of the poverty
level}\label{percent-of-population-below-150-of-the-poverty-level}

\section{- Percent of minority (non-white)
population}\label{percent-of-minority-non-white-population}

\section{- Percent of population without health insurance
coverage}\label{percent-of-population-without-health-insurance-coverage}

\section{Data Wrangling Process}\label{data-wrangling-process}

\section{To integrate the PM2.5 and SVI data, an inner join was
performed on the county FIPS
code}\label{to-integrate-the-pm2.5-and-svi-data-an-inner-join-was-performed-on-the-county-fips-code}

\section{to create a merged dataset for analysis. This allowed us to
examine the
relationships}\label{to-create-a-merged-dataset-for-analysis.-this-allowed-us-to-examine-the-relationships}

\section{between air pollution levels and socioeconomic factors at the
county
level.}\label{between-air-pollution-levels-and-socioeconomic-factors-at-the-county-level.}

\section{Dataset Structure Summary}\label{dataset-structure-summary}

\section{The final dataset has the following
structure:}\label{the-final-dataset-has-the-following-structure}

\section{\textbar{} Column Name \textbar{} Data Type \textbar{}
Description \textbar{}}\label{column-name-data-type-description}

\section{\textbar-------------\textbar-----------\textbar-------------\textbar{}}\label{section}

\section{\textbar{} County FIPS Code \textbar{} Character \textbar{}
Unique identifier for each county
\textbar{}}\label{county-fips-code-character-unique-identifier-for-each-county}

\section{\textbar{} County \textbar{} Character \textbar{} Name of the
county \textbar{}}\label{county-character-name-of-the-county}

\section{\textbar{} Percent\_Below\_150\_Poverty \textbar{} Numeric
\textbar{} Percentage of population below 150\% of the poverty level
\textbar{}}\label{percent_below_150_poverty-numeric-percentage-of-population-below-150-of-the-poverty-level}

\section{\textbar{} Percent\_Uninsured \textbar{} Numeric \textbar{}
Percentage of population without health insurance coverage
\textbar{}}\label{percent_uninsured-numeric-percentage-of-population-without-health-insurance-coverage}

\section{\textbar{} Minority\_Percentage \textbar{} Numeric \textbar{}
Percentage of minority (non-white) population
\textbar{}}\label{minority_percentage-numeric-percentage-of-minority-non-white-population}

\section{\textbar{} yearly\_avg\_PM25\_2000 \textbar{} Numeric
\textbar{} Yearly average PM2.5 concentration in 2000
\textbar{}}\label{yearly_avg_pm25_2000-numeric-yearly-average-pm2.5-concentration-in-2000}

\section{\textbar{} yearly\_avg\_PM25\_2022 \textbar{} Numeric
\textbar{} Yearly average PM2.5 concentration in 2022
\textbar{}}\label{yearly_avg_pm25_2022-numeric-yearly-average-pm2.5-concentration-in-2022}

\section{By combining the air quality and socioeconomic data, this
dataset enables the
investigation}\label{by-combining-the-air-quality-and-socioeconomic-data-this-dataset-enables-the-investigation}

\section{of the relationships between environmental exposures and
demographic factors
across}\label{of-the-relationships-between-environmental-exposures-and-demographic-factors-across}

\section{California counties over the 22-year period from 2000 to
2022.}\label{california-counties-over-the-22-year-period-from-2000-to-2022.}

\newpage

\section{Exploratory Analysis}\label{exploratory-analysis}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Svi\_data\_2022 }\OtherTok{\textless{}{-}}\NormalTok{ SVI\_CA\_County\_2022 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(COUNTY, FIPS, EP\_POV150, E\_MINRTY, E\_TOTPOP, EP\_UNINSUR) }\SpecialCharTok{\%\textgreater{}\%} \CommentTok{\# Include uninsured percentage}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{FIPS =} \FunctionTok{sub}\NormalTok{(}\StringTok{"\^{}06"}\NormalTok{, }\StringTok{""}\NormalTok{, FIPS),}
    \AttributeTok{Minority\_Percentage =}\NormalTok{ (E\_MINRTY }\SpecialCharTok{/}\NormalTok{ E\_TOTPOP) }\SpecialCharTok{*} \DecValTok{100} \CommentTok{\# Calculate minority percentage}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{rename}\NormalTok{(}
    \AttributeTok{County =}\NormalTok{ COUNTY,}
    \StringTok{\textasciigrave{}}\AttributeTok{County FIPS Code}\StringTok{\textasciigrave{}} \OtherTok{=}\NormalTok{ FIPS,}
    \AttributeTok{Percent\_Below\_150\_Poverty =}\NormalTok{ EP\_POV150,}
    \AttributeTok{Percent\_Uninsured =}\NormalTok{ EP\_UNINSUR }\CommentTok{\# Add a new column for uninsured percentage}
\NormalTok{  )}

\CommentTok{\# View the updated data}
\FunctionTok{head}\NormalTok{(Svi\_data\_2022)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 7
##   County           `County FIPS Code` Percent_Below_150_Pove~1 E_MINRTY E_TOTPOP
##   <chr>            <chr>                                 <dbl>    <dbl>    <dbl>
## 1 Alameda County   001                                    14.1  1176371  1663823
## 2 Alpine County    003                                    18.3      635     1515
## 3 Amador County    005                                    14.8    10184    40577
## 4 Butte County     007                                    28.2    66604   213605
## 5 Calaveras County 009                                    21.4     9927    45674
## 6 Colusa County    011                                    22.6    14508    21811
## # i abbreviated name: 1: Percent_Below_150_Poverty
## # i 2 more variables: Percent_Uninsured <dbl>, Minority_Percentage <dbl>
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Svi\_data\_2000 }\OtherTok{\textless{}{-}}\NormalTok{ SVI\_CA\_County\_2000 }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{select}\NormalTok{(COUNTY, CNTY\_FIPS, G3V1N, G1V1N, Totpop2000) }\SpecialCharTok{\%\textgreater{}\%} \CommentTok{\# Include total population column}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{Percent\_Below\_Poverty =}\NormalTok{ (G1V1N }\SpecialCharTok{/}\NormalTok{ Totpop2000) }\SpecialCharTok{*} \DecValTok{100}\NormalTok{, }\CommentTok{\# Calculate poverty percentage}
    \AttributeTok{Minority\_Percentage =}\NormalTok{ (G3V1N }\SpecialCharTok{/}\NormalTok{ Totpop2000) }\SpecialCharTok{*} \DecValTok{100}\NormalTok{,  }\CommentTok{\# Calculate minority percentage}
    \AttributeTok{FIPS =} \FunctionTok{sub}\NormalTok{(}\StringTok{"\^{}06"}\NormalTok{, }\StringTok{""}\NormalTok{, CNTY\_FIPS)}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{rename}\NormalTok{(}
    \AttributeTok{County =}\NormalTok{ COUNTY,}
    \StringTok{\textasciigrave{}}\AttributeTok{County FIPS Code}\StringTok{\textasciigrave{}} \OtherTok{=}\NormalTok{ CNTY\_FIPS}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Fixing date parsing for PM2.5 2022 dataset}
\NormalTok{PM2\_5\_2022 }\OtherTok{\textless{}{-}}\NormalTok{ PM2\_5\_2022 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Date =} \FunctionTok{parse\_date}\NormalTok{(Date, }\AttributeTok{format =} \StringTok{"\%m/\%d/\%Y"}\NormalTok{)) }\CommentTok{\# Corrected format}

\CommentTok{\# Calculate the daily mean PM2.5 for each date within each group}
\CommentTok{\# Calculate the yearly average daily mean PM2.5 concentration per county}
\NormalTok{PM2\_5\_2022\_result }\OtherTok{\textless{}{-}}\NormalTok{ PM2\_5\_2022 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{year =} \FunctionTok{year}\NormalTok{(Date)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(}\StringTok{\textasciigrave{}}\AttributeTok{County FIPS Code}\StringTok{\textasciigrave{}}\NormalTok{, year) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\StringTok{\textasciigrave{}}\AttributeTok{Daily Mean PM2.5 Concentration}\StringTok{\textasciigrave{}} \OtherTok{=} \FunctionTok{mean}\NormalTok{(}\StringTok{\textasciigrave{}}\AttributeTok{Daily Mean PM2.5 Concentration}\StringTok{\textasciigrave{}}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{yearly\_avg\_PM25 =} \FunctionTok{mean}\NormalTok{(}\StringTok{\textasciigrave{}}\AttributeTok{Daily Mean PM2.5 Concentration}\StringTok{\textasciigrave{}}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` has grouped output by 'County FIPS Code'. You can override using
## the `.groups` argument.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(PM2\_5\_2022\_result)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 50 x 2
##    `County FIPS Code` yearly_avg_PM25
##    <chr>                        <dbl>
##  1 001                           8.20
##  2 007                           6.19
##  3 009                           6.04
##  4 011                           7.61
##  5 013                           8.25
##  6 015                           4.97
##  7 017                           4.07
##  8 019                          10.2 
##  9 021                           5.34
## 10 023                           6.76
## # i 40 more rows
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Fixing date parsing for PM2.5 2000 dataset}
\NormalTok{PM2\_5\_2000 }\OtherTok{\textless{}{-}}\NormalTok{ PM2\_5\_2000 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Date =} \FunctionTok{parse\_date}\NormalTok{(Date, }\AttributeTok{format =} \StringTok{"\%m/\%d/\%Y"}\NormalTok{)) }\CommentTok{\# Corrected format}

\CommentTok{\# Calculate the daily mean PM2.5 for each date within each group}
\CommentTok{\# Calculate the yearly average daily mean PM2.5 concentration per county}
\NormalTok{PM2\_5\_2000\_result }\OtherTok{\textless{}{-}}\NormalTok{ PM2\_5\_2000 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{year =} \FunctionTok{year}\NormalTok{(Date)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(}\StringTok{\textasciigrave{}}\AttributeTok{County FIPS Code}\StringTok{\textasciigrave{}}\NormalTok{, year) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\StringTok{\textasciigrave{}}\AttributeTok{Daily Mean PM2.5 Concentration}\StringTok{\textasciigrave{}} \OtherTok{=} \FunctionTok{mean}\NormalTok{(}\StringTok{\textasciigrave{}}\AttributeTok{Daily Mean PM2.5 Concentration}\StringTok{\textasciigrave{}}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{yearly\_avg\_PM25 =} \FunctionTok{mean}\NormalTok{(}\StringTok{\textasciigrave{}}\AttributeTok{Daily Mean PM2.5 Concentration}\StringTok{\textasciigrave{}}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` has grouped output by 'County FIPS Code'. You can override using
## the `.groups` argument.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(PM2\_5\_2000\_result)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 48 x 2
##    `County FIPS Code` yearly_avg_PM25
##    <chr>                        <dbl>
##  1 001                          12.0 
##  2 007                          15.8 
##  3 009                           8.98
##  4 011                           8.20
##  5 013                          12.9 
##  6 015                           3.86
##  7 017                           4.86
##  8 019                          20.4 
##  9 023                           9.27
## 10 025                          14.4 
## # i 38 more rows
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Merge SVI and PM2.5 datasets for 2000}
\NormalTok{Merged\_2000 }\OtherTok{\textless{}{-}} \FunctionTok{inner\_join}\NormalTok{(Svi\_data\_2000, PM2\_5\_2000\_result, }\AttributeTok{by =} \StringTok{"County FIPS Code"}\NormalTok{)}

\CommentTok{\# Merge SVI and PM2.5 datasets for 2022}
\NormalTok{Merged\_2022 }\OtherTok{\textless{}{-}} \FunctionTok{inner\_join}\NormalTok{(Svi\_data\_2022, PM2\_5\_2022\_result, }\AttributeTok{by =} \StringTok{"County FIPS Code"}\NormalTok{)}

\CommentTok{\# Standardize county names in 2022 dataset by removing "County"}
\NormalTok{Merged\_2022 }\OtherTok{\textless{}{-}}\NormalTok{ Merged\_2022 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{County =} \FunctionTok{str\_remove}\NormalTok{(County, }\StringTok{" County$"}\NormalTok{))}

\FunctionTok{head}\NormalTok{(Merged\_2000)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 9
##   County       `County FIPS Code`  G3V1N  G1V1N Totpop2000 Percent_Below_Poverty
##   <chr>        <chr>               <dbl>  <dbl>      <dbl>                 <dbl>
## 1 Alameda      001                854498 156804    1443741                 10.9 
## 2 Butte        007                 41029  39148     203171                 19.3 
## 3 Calaveras    009                  5026   4704      40554                 11.6 
## 4 Colusa       011                  9865   2964      18804                 15.8 
## 5 Contra Costa 013                400979  71575     948816                  7.54
## 6 Del Norte    015                  8235   4765      27507                 17.3 
## # i 3 more variables: Minority_Percentage <dbl>, FIPS <chr>,
## #   yearly_avg_PM25 <dbl>
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(Merged\_2022)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 8
##   County       `County FIPS Code` Percent_Below_150_Poverty E_MINRTY E_TOTPOP
##   <chr>        <chr>                                  <dbl>    <dbl>    <dbl>
## 1 Alameda      001                                     14.1  1176371  1663823
## 2 Butte        007                                     28.2    66604   213605
## 3 Calaveras    009                                     21.4     9927    45674
## 4 Colusa       011                                     22.6    14508    21811
## 5 Contra Costa 013                                     13.5   690897  1162648
## 6 Del Norte    015                                     25.3    10786    27462
## # i 3 more variables: Percent_Uninsured <dbl>, Minority_Percentage <dbl>,
## #   yearly_avg_PM25 <dbl>
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Load the shapefile}
\FunctionTok{library}\NormalTok{(sf) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Linking to GEOS 3.10.2, GDAL 3.4.1, PROJ 8.2.1; sf_use_s2() is TRUE
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{shapefile\_path }\OtherTok{\textless{}{-}} \StringTok{"DATA/CA\_Counties.shp"}  \CommentTok{\# Replace with the actual path}
\NormalTok{counties }\OtherTok{\textless{}{-}} \FunctionTok{st\_read}\NormalTok{(shapefile\_path)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Reading layer `CA_Counties' from data source 
##   `/home/guest/Project_main/DATA/CA_Counties.shp' using driver `ESRI Shapefile'
## Simple feature collection with 58 features and 19 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -13857270 ymin: 3832931 xmax: -12705030 ymax: 5162404
## Projected CRS: WGS 84 / Pseudo-Mercator
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Check the structure of the shapefile}
\FunctionTok{print}\NormalTok{(counties)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Simple feature collection with 58 features and 19 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -13857270 ymin: 3832931 xmax: -12705030 ymax: 5162404
## Projected CRS: WGS 84 / Pseudo-Mercator
## First 10 features:
##    STATEFP COUNTYFP COUNTYNS GEOID          NAME             NAMELSAD LSAD
## 1       06      091 00277310 06091        Sierra        Sierra County   06
## 2       06      067 00277298 06067    Sacramento    Sacramento County   06
## 3       06      083 00277306 06083 Santa Barbara Santa Barbara County   06
## 4       06      009 01675885 06009     Calaveras     Calaveras County   06
## 5       06      111 00277320 06111       Ventura       Ventura County   06
## 6       06      037 00277283 06037   Los Angeles   Los Angeles County   06
## 7       06      097 01657246 06097        Sonoma        Sonoma County   06
## 8       06      031 00277280 06031         Kings         Kings County   06
## 9       06      073 00277301 06073     San Diego     San Diego County   06
## 10      06      061 00277295 06061        Placer        Placer County   06
##    CLASSFP MTFCC CSAFP CBSAFP METDIVFP FUNCSTAT       ALAND     AWATER
## 1       H1 G4020  <NA>   <NA>     <NA>        A  2468694583   23299110
## 2       H1 G4020   472  40900     <NA>        A  2499983887   75425434
## 3       H1 G4020  <NA>  42200     <NA>        A  7084063392 2729751706
## 4       H1 G4020  <NA>   <NA>     <NA>        A  2641784992   43841871
## 5       H1 G4020   348  37100     <NA>        A  4771987962  947345370
## 6       H1 G4020   348  31080    31084        A 10511861492 1793485467
## 7       H1 G4020   488  42220     <NA>        A  4080764059  498182342
## 8       H1 G4020   260  25260     <NA>        A  3600883803    3162664
## 9       H1 G4020  <NA>  41740     <NA>        A 10904373558  817404622
## 10      H1 G4020   472  40900     <NA>        A  3644306246  246466620
##       INTPTLAT     INTPTLON Shape_Leng  Shape_Area
## 1  +39.5769252 -120.5219926   375602.8  4200449583
## 2  +38.4500161 -121.3404408   406584.2  4205515610
## 3  +34.5370572 -120.0399729   891686.7 14498407802
## 4  +38.1838996 -120.5614415   367005.9  4356213313
## 5  +34.3587415 -119.1331432   527772.2  8413293072
## 6  +34.1963983 -118.2618616   883876.9 18034312799
## 7  +38.5251824 -122.9261095   486513.3  7492856117
## 8  +36.0724780 -119.8155301   354668.8  5528559883
## 9  +33.0236041 -116.7761174   553042.6 16722013504
## 10 +39.0620323 -120.7227181   533218.2  6462795400
##                          geometry
## 1  MULTIPOLYGON (((-13431320 4...
## 2  MULTIPOLYGON (((-13490651 4...
## 3  MULTIPOLYGON (((-13440081 4...
## 4  MULTIPOLYGON (((-13428575 4...
## 5  MULTIPOLYGON (((-13283669 4...
## 6  MULTIPOLYGON (((-13214003 4...
## 7  MULTIPOLYGON (((-13685070 4...
## 8  MULTIPOLYGON (((-13353768 4...
## 9  MULTIPOLYGON (((-13073076 3...
## 10 MULTIPOLYGON (((-13476944 4...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Merge the shapefile with your dataset}
\NormalTok{county\_map }\OtherTok{\textless{}{-}}\NormalTok{ counties }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{left\_join}\NormalTok{(Merged\_2022, }\AttributeTok{by =} \FunctionTok{c}\NormalTok{(}\StringTok{"COUNTYFP"} \OtherTok{=} \StringTok{"County FIPS Code"}\NormalTok{))}

\CommentTok{\# Map of PM2.5 Levels}
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ county\_map) }\SpecialCharTok{+}
  \FunctionTok{geom\_sf}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{fill =}\NormalTok{ yearly\_avg\_PM25)) }\SpecialCharTok{+}  \CommentTok{\# Fill color based on PM2.5 levels}
  \FunctionTok{scale\_fill\_viridis\_c}\NormalTok{(}\AttributeTok{option =} \StringTok{"plasma"}\NormalTok{,}\AttributeTok{direction =} \SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, }\AttributeTok{name =} \StringTok{"PM2.5 (μg/m³)"}\NormalTok{) }\SpecialCharTok{+}  \CommentTok{\# Color scale}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"PM2.5 Levels Across California (2022)"}\NormalTok{,}
    \AttributeTok{caption =} \StringTok{"Data Source: EPA and CDC"}
\NormalTok{  ) }\SpecialCharTok{+}
\NormalTok{  mytheme}
\end{Highlighting}
\end{Shaded}

\includegraphics{Project_Template_files/figure-latex/unnamed-chunk-4-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Load the shapefile}
\FunctionTok{library}\NormalTok{(sf) }

\NormalTok{shapefile\_path }\OtherTok{\textless{}{-}} \StringTok{"DATA/CA\_Counties.shp"}  \CommentTok{\# Replace with the actual path}
\NormalTok{counties }\OtherTok{\textless{}{-}} \FunctionTok{st\_read}\NormalTok{(shapefile\_path)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Reading layer `CA_Counties' from data source 
##   `/home/guest/Project_main/DATA/CA_Counties.shp' using driver `ESRI Shapefile'
## Simple feature collection with 58 features and 19 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -13857270 ymin: 3832931 xmax: -12705030 ymax: 5162404
## Projected CRS: WGS 84 / Pseudo-Mercator
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Check the structure of the shapefile}
\FunctionTok{print}\NormalTok{(counties)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Simple feature collection with 58 features and 19 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -13857270 ymin: 3832931 xmax: -12705030 ymax: 5162404
## Projected CRS: WGS 84 / Pseudo-Mercator
## First 10 features:
##    STATEFP COUNTYFP COUNTYNS GEOID          NAME             NAMELSAD LSAD
## 1       06      091 00277310 06091        Sierra        Sierra County   06
## 2       06      067 00277298 06067    Sacramento    Sacramento County   06
## 3       06      083 00277306 06083 Santa Barbara Santa Barbara County   06
## 4       06      009 01675885 06009     Calaveras     Calaveras County   06
## 5       06      111 00277320 06111       Ventura       Ventura County   06
## 6       06      037 00277283 06037   Los Angeles   Los Angeles County   06
## 7       06      097 01657246 06097        Sonoma        Sonoma County   06
## 8       06      031 00277280 06031         Kings         Kings County   06
## 9       06      073 00277301 06073     San Diego     San Diego County   06
## 10      06      061 00277295 06061        Placer        Placer County   06
##    CLASSFP MTFCC CSAFP CBSAFP METDIVFP FUNCSTAT       ALAND     AWATER
## 1       H1 G4020  <NA>   <NA>     <NA>        A  2468694583   23299110
## 2       H1 G4020   472  40900     <NA>        A  2499983887   75425434
## 3       H1 G4020  <NA>  42200     <NA>        A  7084063392 2729751706
## 4       H1 G4020  <NA>   <NA>     <NA>        A  2641784992   43841871
## 5       H1 G4020   348  37100     <NA>        A  4771987962  947345370
## 6       H1 G4020   348  31080    31084        A 10511861492 1793485467
## 7       H1 G4020   488  42220     <NA>        A  4080764059  498182342
## 8       H1 G4020   260  25260     <NA>        A  3600883803    3162664
## 9       H1 G4020  <NA>  41740     <NA>        A 10904373558  817404622
## 10      H1 G4020   472  40900     <NA>        A  3644306246  246466620
##       INTPTLAT     INTPTLON Shape_Leng  Shape_Area
## 1  +39.5769252 -120.5219926   375602.8  4200449583
## 2  +38.4500161 -121.3404408   406584.2  4205515610
## 3  +34.5370572 -120.0399729   891686.7 14498407802
## 4  +38.1838996 -120.5614415   367005.9  4356213313
## 5  +34.3587415 -119.1331432   527772.2  8413293072
## 6  +34.1963983 -118.2618616   883876.9 18034312799
## 7  +38.5251824 -122.9261095   486513.3  7492856117
## 8  +36.0724780 -119.8155301   354668.8  5528559883
## 9  +33.0236041 -116.7761174   553042.6 16722013504
## 10 +39.0620323 -120.7227181   533218.2  6462795400
##                          geometry
## 1  MULTIPOLYGON (((-13431320 4...
## 2  MULTIPOLYGON (((-13490651 4...
## 3  MULTIPOLYGON (((-13440081 4...
## 4  MULTIPOLYGON (((-13428575 4...
## 5  MULTIPOLYGON (((-13283669 4...
## 6  MULTIPOLYGON (((-13214003 4...
## 7  MULTIPOLYGON (((-13685070 4...
## 8  MULTIPOLYGON (((-13353768 4...
## 9  MULTIPOLYGON (((-13073076 3...
## 10 MULTIPOLYGON (((-13476944 4...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Merge the shapefile with your dataset}
\NormalTok{county\_map }\OtherTok{\textless{}{-}}\NormalTok{ counties }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{left\_join}\NormalTok{(Merged\_2000, }\AttributeTok{by =} \FunctionTok{c}\NormalTok{(}\StringTok{"COUNTYFP"} \OtherTok{=} \StringTok{"County FIPS Code"}\NormalTok{))}

\CommentTok{\# Map of PM2.5 Levels}
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ county\_map) }\SpecialCharTok{+}
  \FunctionTok{geom\_sf}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{fill =}\NormalTok{ yearly\_avg\_PM25)) }\SpecialCharTok{+}  \CommentTok{\# Fill color based on PM2.5 levels}
  \FunctionTok{scale\_fill\_viridis\_c}\NormalTok{(}\AttributeTok{option =} \StringTok{"plasma"}\NormalTok{,}\AttributeTok{direction =} \SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, }\AttributeTok{name =} \StringTok{"PM2.5 (μg/m³)"}\NormalTok{) }\SpecialCharTok{+}  \CommentTok{\# Color scale}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"PM2.5 Levels Across California (2000)"}\NormalTok{,}
    \AttributeTok{caption =} \StringTok{"Data Source: EPA and CDC"}
\NormalTok{  ) }\SpecialCharTok{+}
\NormalTok{  mytheme}
\end{Highlighting}
\end{Shaded}

\includegraphics{Project_Template_files/figure-latex/unnamed-chunk-5-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Adding 100\% poverty level data to the SVI\_CA\_County\_2022 dataset to make it comparable with 2000 data}

\CommentTok{\# Keep only relevant columns and rename them}
\NormalTok{poverty\_data\_2022 }\OtherTok{\textless{}{-}}\NormalTok{ poverty\_data\_2022 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(}
    \StringTok{\textasciigrave{}}\AttributeTok{State FIPS Code}\StringTok{\textasciigrave{}}\NormalTok{,                  }\CommentTok{\# State FIPS Code}
    \StringTok{\textasciigrave{}}\AttributeTok{County FIPS Code}\StringTok{\textasciigrave{}}\NormalTok{,                 }\CommentTok{\# County FIPS Code}
    \StringTok{\textasciigrave{}}\AttributeTok{Poverty Percent, All Ages}\StringTok{\textasciigrave{}}         \CommentTok{\# Percent below 100\% poverty}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{rename}\NormalTok{(}
    \StringTok{\textasciigrave{}}\AttributeTok{Percent\_Below\_Poverty}\StringTok{\textasciigrave{}} \OtherTok{=} \StringTok{\textasciigrave{}}\AttributeTok{Poverty Percent, All Ages}\StringTok{\textasciigrave{}}\NormalTok{,  }\CommentTok{\# Rename for consistency}
\NormalTok{  )}

\CommentTok{\# Filter for California data (State FIPS = 06)}
\NormalTok{california\_poverty }\OtherTok{\textless{}{-}}\NormalTok{ poverty\_data\_2022 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(}\StringTok{\textasciigrave{}}\AttributeTok{State FIPS Code}\StringTok{\textasciigrave{}} \SpecialCharTok{==} \StringTok{"06"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(}\StringTok{\textasciigrave{}}\AttributeTok{County FIPS Code}\StringTok{\textasciigrave{}}\NormalTok{, }\StringTok{\textasciigrave{}}\AttributeTok{Percent\_Below\_Poverty}\StringTok{\textasciigrave{}}\NormalTok{) }\CommentTok{\# Keep only required columns}

\CommentTok{\# Merge the poverty data into the SVI 2022 dataset}
\NormalTok{Merged\_2022 }\OtherTok{\textless{}{-}}\NormalTok{ Merged\_2022 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{left\_join}\NormalTok{(california\_poverty, }\AttributeTok{by =} \StringTok{"County FIPS Code"}\NormalTok{)}

\CommentTok{\# Inspect the updated dataset}
\FunctionTok{head}\NormalTok{(Merged\_2022)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 9
##   County       `County FIPS Code` Percent_Below_150_Poverty E_MINRTY E_TOTPOP
##   <chr>        <chr>                                  <dbl>    <dbl>    <dbl>
## 1 Alameda      001                                     14.1  1176371  1663823
## 2 Butte        007                                     28.2    66604   213605
## 3 Calaveras    009                                     21.4     9927    45674
## 4 Colusa       011                                     22.6    14508    21811
## 5 Contra Costa 013                                     13.5   690897  1162648
## 6 Del Norte    015                                     25.3    10786    27462
## # i 4 more variables: Percent_Uninsured <dbl>, Minority_Percentage <dbl>,
## #   yearly_avg_PM25 <dbl>, Percent_Below_Poverty <dbl>
\end{verbatim}

\section{CORRELATION ANALYSIS}\label{correlation-analysis}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# This examines associations between PM2.5 and other variables (Percent Uninsured, Percent Below Poverty, Minority Percentage)}

\CommentTok{\# CORRELATION MATRIX {-} 2022}
\CommentTok{\# Test associations between PM2.5 and socioeconomic variables for 2022 data}
\NormalTok{correlation\_matrix\_2022 }\OtherTok{\textless{}{-}} \FunctionTok{cor}\NormalTok{(Merged\_2022[, }\FunctionTok{c}\NormalTok{(}\StringTok{"yearly\_avg\_PM25"}\NormalTok{, }
                                               \StringTok{"Percent\_Uninsured"}\NormalTok{, }
                                               \StringTok{"Percent\_Below\_Poverty"}\NormalTok{, }
                                               \StringTok{"Percent\_Below\_150\_Poverty"}\NormalTok{, }
                                               \StringTok{"Minority\_Percentage"}\NormalTok{)], }
                               \AttributeTok{use =} \StringTok{"complete.obs"}\NormalTok{, }\AttributeTok{method =} \StringTok{"pearson"}\NormalTok{)}

\CommentTok{\# Print the correlation matrix for 2022}
\FunctionTok{print}\NormalTok{(correlation\_matrix\_2022)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                           yearly_avg_PM25 Percent_Uninsured
## yearly_avg_PM25                 1.0000000        0.10152052
## Percent_Uninsured               0.1015205        1.00000000
## Percent_Below_Poverty           0.3833281        0.36294705
## Percent_Below_150_Poverty       0.3447585        0.46532629
## Minority_Percentage             0.3670272        0.06639129
##                           Percent_Below_Poverty Percent_Below_150_Poverty
## yearly_avg_PM25                       0.3833281                 0.3447585
## Percent_Uninsured                     0.3629470                 0.4653263
## Percent_Below_Poverty                 1.0000000                 0.9493793
## Percent_Below_150_Poverty             0.9493793                 1.0000000
## Minority_Percentage                   0.1158359                 0.1187493
##                           Minority_Percentage
## yearly_avg_PM25                    0.36702715
## Percent_Uninsured                  0.06639129
## Percent_Below_Poverty              0.11583589
## Percent_Below_150_Poverty          0.11874926
## Minority_Percentage                1.00000000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(corrplot)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## corrplot 0.94 loaded
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Plot Heatmap for 2022}
\FunctionTok{corrplot}\NormalTok{(correlation\_matrix\_2022, }
         \AttributeTok{method =} \StringTok{"color"}\NormalTok{, }
         \AttributeTok{type =} \StringTok{"upper"}\NormalTok{, }
         \AttributeTok{col =} \FunctionTok{colorRampPalette}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"blue"}\NormalTok{, }\StringTok{"white"}\NormalTok{, }\StringTok{"red"}\NormalTok{))(}\DecValTok{200}\NormalTok{),}
         \AttributeTok{title =} \StringTok{"Correlation Heatmap (2022)"}\NormalTok{, }
         \AttributeTok{tl.col =} \StringTok{"black"}\NormalTok{, }
         \AttributeTok{tl.srt =} \DecValTok{45}\NormalTok{, }
         \AttributeTok{tl.cex =} \FloatTok{0.5}\NormalTok{,}
         \AttributeTok{cl.cex =} \FloatTok{0.5}\NormalTok{, }
         \AttributeTok{mar =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{), }
         \AttributeTok{order =} \StringTok{"hclust"}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Project_Template_files/figure-latex/unnamed-chunk-7-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# CORRELATION MATRIX {-} 2000}
\CommentTok{\# Test associations between PM2.5 and socioeconomic variables for 2000 data}
\NormalTok{correlation\_matrix\_2000 }\OtherTok{\textless{}{-}} \FunctionTok{cor}\NormalTok{(Merged\_2000[, }\FunctionTok{c}\NormalTok{(}\StringTok{"yearly\_avg\_PM25"}\NormalTok{, }
                                               \StringTok{"Percent\_Below\_Poverty"}\NormalTok{, }
                                               \StringTok{"Minority\_Percentage"}\NormalTok{)], }
                               \AttributeTok{use =} \StringTok{"complete.obs"}\NormalTok{, }\AttributeTok{method =} \StringTok{"pearson"}\NormalTok{)}

\CommentTok{\# Print the correlation matrix for 2000}
\FunctionTok{print}\NormalTok{(correlation\_matrix\_2000)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                       yearly_avg_PM25 Percent_Below_Poverty Minority_Percentage
## yearly_avg_PM25             1.0000000             0.1685785           0.6180766
## Percent_Below_Poverty       0.1685785             1.0000000           0.1946454
## Minority_Percentage         0.6180766             0.1946454           1.0000000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Plot Heatmap for 2000}
\FunctionTok{corrplot}\NormalTok{(correlation\_matrix\_2000, }
         \AttributeTok{method =} \StringTok{"color"}\NormalTok{, }
         \AttributeTok{type =} \StringTok{"upper"}\NormalTok{, }
         \AttributeTok{col =} \FunctionTok{colorRampPalette}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"blue"}\NormalTok{, }\StringTok{"white"}\NormalTok{, }\StringTok{"red"}\NormalTok{))(}\DecValTok{200}\NormalTok{),}
         \AttributeTok{title =} \StringTok{"Correlation Heatmap (2022)"}\NormalTok{, }
         \AttributeTok{tl.col =} \StringTok{"black"}\NormalTok{, }
         \AttributeTok{tl.srt =} \DecValTok{45}\NormalTok{, }
         \AttributeTok{tl.cex =} \FloatTok{0.5}\NormalTok{,}
         \AttributeTok{cl.cex =} \FloatTok{0.5}\NormalTok{, }
         \AttributeTok{mar =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{), }
         \AttributeTok{order =} \StringTok{"hclust"}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Project_Template_files/figure-latex/unnamed-chunk-7-2.pdf}

\section{MULTIVARIATE REGRESSION}\label{multivariate-regression}

\section{Note: This is for exploring associations, not
causation.}\label{note-this-is-for-exploring-associations-not-causation.}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# This models PM2.5 as a function of Percent Uninsured, Percent Below Poverty, and Minority Percentage.}
\CommentTok{\# This regression is for associational analysis, not to infer causation.}

\CommentTok{\# REGRESSION MODELS {-} 2022}
\CommentTok{\# MODEL 1: Using Percent Below Poverty}
\NormalTok{pm25\_model\_2022\_poverty }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(yearly\_avg\_PM25 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Percent\_Uninsured }\SpecialCharTok{+}\NormalTok{ Percent\_Below\_Poverty }\SpecialCharTok{+}\NormalTok{ Minority\_Percentage, }\AttributeTok{data =}\NormalTok{ Merged\_2022)}
\FunctionTok{summary}\NormalTok{(pm25\_model\_2022\_poverty)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = yearly_avg_PM25 ~ Percent_Uninsured + Percent_Below_Poverty + 
##     Minority_Percentage, data = Merged_2022)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.7228 -1.6085  0.1525  1.1774  4.8895 
## 
## Coefficients:
##                       Estimate Std. Error t value Pr(>|t|)  
## (Intercept)            3.35826    1.33486   2.516   0.0154 *
## Percent_Uninsured     -0.05278    0.13730  -0.384   0.7025  
## Percent_Below_Poverty  0.21472    0.08089   2.655   0.0109 *
## Minority_Percentage    0.03864    0.01509   2.561   0.0138 *
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 2.062 on 46 degrees of freedom
## Multiple R-squared:  0.2548, Adjusted R-squared:  0.2062 
## F-statistic: 5.244 on 3 and 46 DF,  p-value: 0.003386
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# MODEL 2: Using Percent Below 150\% Poverty}
\NormalTok{pm25\_model\_2022\_150\_poverty }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(yearly\_avg\_PM25 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Percent\_Uninsured }\SpecialCharTok{+}\NormalTok{ Percent\_Below\_150\_Poverty }\SpecialCharTok{+}\NormalTok{ Minority\_Percentage, }\AttributeTok{data =}\NormalTok{ Merged\_2022)}
\FunctionTok{summary}\NormalTok{(pm25\_model\_2022\_150\_poverty)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = yearly_avg_PM25 ~ Percent_Uninsured + Percent_Below_150_Poverty + 
##     Minority_Percentage, data = Merged_2022)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.7002 -1.5559  0.1983  0.9924  5.1776 
## 
## Coefficients:
##                           Estimate Std. Error t value Pr(>|t|)   
## (Intercept)                3.77577    1.30961   2.883  0.00597 **
## Percent_Uninsured         -0.08029    0.14673  -0.547  0.58690   
## Percent_Below_150_Poverty  0.11920    0.05106   2.335  0.02399 * 
## Minority_Percentage        0.03904    0.01532   2.548  0.01424 * 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 2.094 on 46 degrees of freedom
## Multiple R-squared:  0.2317, Adjusted R-squared:  0.1816 
## F-statistic: 4.624 on 3 and 46 DF,  p-value: 0.006565
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# REGRESSION MODEL {-} 2000}
\CommentTok{\# Association between PM2.5 and socioeconomic variables}
\NormalTok{pm25\_model\_2000 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(yearly\_avg\_PM25 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Percent\_Below\_Poverty }\SpecialCharTok{+}\NormalTok{ Minority\_Percentage, }\AttributeTok{data =}\NormalTok{ Merged\_2000)}
\FunctionTok{summary}\NormalTok{(pm25\_model\_2000)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = yearly_avg_PM25 ~ Percent_Below_Poverty + Minority_Percentage, 
##     data = Merged_2000)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -9.2839 -2.8851  0.4562  2.6248  9.7625 
## 
## Coefficients:
##                       Estimate Std. Error t value Pr(>|t|)    
## (Intercept)            4.12689    2.12746   1.940   0.0587 .  
## Percent_Below_Poverty  0.05574    0.13247   0.421   0.6759    
## Minority_Percentage    0.17360    0.03403   5.102 6.55e-06 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 4.217 on 45 degrees of freedom
## Multiple R-squared:  0.3844, Adjusted R-squared:  0.3571 
## F-statistic: 14.05 on 2 and 45 DF,  p-value: 1.814e-05
\end{verbatim}

\#Interpretation:

\#Both models for 2022 show that Minority Percentage and poverty
measures (whether below poverty or 150\% poverty) are significantly
associated with higher PM2.5 levels, supporting the hypothesis that
vulnerable populations are more exposed to pollution. However, Percent
Uninsured does not show a significant relationship with PM2.5 in either
model. The models explain about 23--25\% of the variance, indicating
moderate explanatory power.The 2000 regression model reveals a
significant positive association between Minority Percentage and PM2.5
levels but Percent Below Poverty shows no significant relationship with
PM2.5. This differs from the 2022 results, highlighting a possible shift
over time in how demographic and socioeconomic factors relate to
pollution exposure.

\#Comparitive Analysis between 2000 and 2022

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Merge the 2000 and 2022 datasets for paired analysis}
\NormalTok{differences }\OtherTok{\textless{}{-}}\NormalTok{ Merged\_2000 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{inner\_join}\NormalTok{(Merged\_2022, }\AttributeTok{by =} \StringTok{"County FIPS Code"}\NormalTok{, }\AttributeTok{suffix =} \FunctionTok{c}\NormalTok{(}\StringTok{"\_2000"}\NormalTok{, }\StringTok{"\_2022"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{PM2.5\_Difference =}\NormalTok{ yearly\_avg\_PM25\_2022 }\SpecialCharTok{{-}}\NormalTok{ yearly\_avg\_PM25\_2000,}
    \AttributeTok{Poverty\_Difference =}\NormalTok{ Percent\_Below\_Poverty\_2022 }\SpecialCharTok{{-}}\NormalTok{ Percent\_Below\_Poverty\_2000,}
    \AttributeTok{Minority\_Difference =}\NormalTok{ Minority\_Percentage\_2022 }\SpecialCharTok{{-}}\NormalTok{ Minority\_Percentage\_2000,}
    \AttributeTok{PM2.5\_Change =} \FunctionTok{ifelse}\NormalTok{(PM2}\FloatTok{.5}\NormalTok{\_Difference }\SpecialCharTok{\textgreater{}} \FloatTok{0.01}\NormalTok{, }\StringTok{"Increase"}\NormalTok{,}
                          \FunctionTok{ifelse}\NormalTok{(PM2}\FloatTok{.5}\NormalTok{\_Difference }\SpecialCharTok{\textless{}} \SpecialCharTok{{-}}\FloatTok{0.01}\NormalTok{, }\StringTok{"Decrease"}\NormalTok{, }\StringTok{"No Change"}\NormalTok{)),}
    \AttributeTok{Poverty\_Change =} \FunctionTok{ifelse}\NormalTok{(Poverty\_Difference }\SpecialCharTok{\textgreater{}} \FloatTok{0.01}\NormalTok{, }\StringTok{"Increase"}\NormalTok{,}
                            \FunctionTok{ifelse}\NormalTok{(Poverty\_Difference }\SpecialCharTok{\textless{}} \SpecialCharTok{{-}}\FloatTok{0.01}\NormalTok{, }\StringTok{"Decrease"}\NormalTok{, }\StringTok{"No Change"}\NormalTok{)),}
    \AttributeTok{Minority\_Change =} \FunctionTok{ifelse}\NormalTok{(Minority\_Difference }\SpecialCharTok{\textgreater{}} \FloatTok{0.01}\NormalTok{, }\StringTok{"Increase"}\NormalTok{,}
                             \FunctionTok{ifelse}\NormalTok{(Minority\_Difference }\SpecialCharTok{\textless{}} \SpecialCharTok{{-}}\FloatTok{0.01}\NormalTok{, }\StringTok{"Decrease"}\NormalTok{, }\StringTok{"No Change"}\NormalTok{))}
\NormalTok{  )}


\CommentTok{\# County{-}Level Change Summary}
\CommentTok{\# Paired Comparison Results}
\NormalTok{paired\_comparison\_results }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{Metric =} \FunctionTok{c}\NormalTok{(}\StringTok{"PM2.5"}\NormalTok{, }\StringTok{"Percent Below Poverty"}\NormalTok{, }\StringTok{"Minority Percentage"}\NormalTok{),}
  \AttributeTok{Mean\_Change =} \FunctionTok{c}\NormalTok{(}
    \FunctionTok{mean}\NormalTok{(differences}\SpecialCharTok{$}\NormalTok{PM2}\FloatTok{.5}\NormalTok{\_Difference, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \FunctionTok{mean}\NormalTok{(differences}\SpecialCharTok{$}\NormalTok{Poverty\_Difference, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \FunctionTok{mean}\NormalTok{(differences}\SpecialCharTok{$}\NormalTok{Minority\_Difference, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{  ),}
  \AttributeTok{T\_Statistic =} \FunctionTok{c}\NormalTok{(}
    \FunctionTok{t.test}\NormalTok{(differences}\SpecialCharTok{$}\NormalTok{PM2}\FloatTok{.5}\NormalTok{\_Difference, }\AttributeTok{mu =} \DecValTok{0}\NormalTok{)}\SpecialCharTok{$}\NormalTok{statistic,}
    \FunctionTok{t.test}\NormalTok{(differences}\SpecialCharTok{$}\NormalTok{Poverty\_Difference, }\AttributeTok{mu =} \DecValTok{0}\NormalTok{)}\SpecialCharTok{$}\NormalTok{statistic,}
    \FunctionTok{t.test}\NormalTok{(differences}\SpecialCharTok{$}\NormalTok{Minority\_Difference, }\AttributeTok{mu =} \DecValTok{0}\NormalTok{)}\SpecialCharTok{$}\NormalTok{statistic}
\NormalTok{  ),}
  \AttributeTok{P\_Value =} \FunctionTok{c}\NormalTok{(}
    \FunctionTok{t.test}\NormalTok{(differences}\SpecialCharTok{$}\NormalTok{PM2}\FloatTok{.5}\NormalTok{\_Difference, }\AttributeTok{mu =} \DecValTok{0}\NormalTok{)}\SpecialCharTok{$}\NormalTok{p.value,}
    \FunctionTok{t.test}\NormalTok{(differences}\SpecialCharTok{$}\NormalTok{Poverty\_Difference, }\AttributeTok{mu =} \DecValTok{0}\NormalTok{)}\SpecialCharTok{$}\NormalTok{p.value,}
    \FunctionTok{t.test}\NormalTok{(differences}\SpecialCharTok{$}\NormalTok{Minority\_Difference, }\AttributeTok{mu =} \DecValTok{0}\NormalTok{)}\SpecialCharTok{$}\NormalTok{p.value}
\NormalTok{  )}
\NormalTok{)}

\NormalTok{county\_level\_summary }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{Metric =} \FunctionTok{c}\NormalTok{(}\StringTok{"PM2.5"}\NormalTok{, }\StringTok{"Percent Below Poverty"}\NormalTok{, }\StringTok{"Minority Percentage"}\NormalTok{),}
  \AttributeTok{Increase =} \FunctionTok{sapply}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"PM2.5\_Change"}\NormalTok{, }\StringTok{"Poverty\_Change"}\NormalTok{, }\StringTok{"Minority\_Change"}\NormalTok{), }
                    \ControlFlowTok{function}\NormalTok{(col) }\FunctionTok{sum}\NormalTok{(differences[[col]] }\SpecialCharTok{==} \StringTok{"Increase"}\NormalTok{)),}
  \AttributeTok{Decrease =} \FunctionTok{sapply}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"PM2.5\_Change"}\NormalTok{, }\StringTok{"Poverty\_Change"}\NormalTok{, }\StringTok{"Minority\_Change"}\NormalTok{), }
                    \ControlFlowTok{function}\NormalTok{(col) }\FunctionTok{sum}\NormalTok{(differences[[col]] }\SpecialCharTok{==} \StringTok{"Decrease"}\NormalTok{)),}
  \AttributeTok{No\_Change =} \FunctionTok{sapply}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"PM2.5\_Change"}\NormalTok{, }\StringTok{"Poverty\_Change"}\NormalTok{, }\StringTok{"Minority\_Change"}\NormalTok{), }
                     \ControlFlowTok{function}\NormalTok{(col) }\FunctionTok{sum}\NormalTok{(differences[[col]] }\SpecialCharTok{==} \StringTok{"No Change"}\NormalTok{))}
\NormalTok{)}

\CommentTok{\# PM2.5 Changes By Poverty Trends}
\NormalTok{poverty\_pm25\_summary }\OtherTok{\textless{}{-}}\NormalTok{ differences }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(Poverty\_Change) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{Average\_PM2.5\_Change =} \FunctionTok{mean}\NormalTok{(PM2}\FloatTok{.5}\NormalTok{\_Difference, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{Number\_of\_Counties =} \FunctionTok{n}\NormalTok{()}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(Poverty\_Change }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\StringTok{"Increase"}\NormalTok{, }\StringTok{"Decrease"}\NormalTok{))}


\CommentTok{\# Print the results}
\CommentTok{\# Print the Paired Comparison Table}
\FunctionTok{print}\NormalTok{(}\StringTok{"Paired Comparison Results for 2000 vs. 2022"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Paired Comparison Results for 2000 vs. 2022"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(paired\_comparison\_results)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                  Metric Mean_Change T_Statistic      P_Value
## 1                 PM2.5  -3.7641671   -5.645080 9.823930e-07
## 2 Percent Below Poverty  -0.7963269   -2.944006 5.065187e-03
## 3   Minority Percentage  12.3181269   24.042011 1.091449e-27
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\StringTok{"County{-}Level Change Summary"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "County-Level Change Summary"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(county\_level\_summary)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                                Metric Increase Decrease No_Change
## PM2.5_Change                    PM2.5        8       39         0
## Poverty_Change  Percent Below Poverty       17       30         0
## Minority_Change   Minority Percentage       47        0         0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\StringTok{"PM2.5 Changes By Poverty Trends"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "PM2.5 Changes By Poverty Trends"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(poverty\_pm25\_summary)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 2 x 3
##   Poverty_Change Average_PM2.5_Change Number_of_Counties
##   <chr>                         <dbl>              <int>
## 1 Decrease                      -4.31                 30
## 2 Increase                      -2.81                 17
\end{verbatim}

\#Interpretation: Over the past 22 years, there has been a significant
reduction in PM2.5 levels and poverty rates, indicating improvements in
air quality and socioeconomic conditions. However, the minority
population percentage has significantly increased, reflecting notable
demographic shifts. These trends suggest progress in environmental and
economic factors, alongside evolving population dynamics, which may have
implications for policy and resource allocation in addressing
environmental justice and equity. In counties where poverty decreased,
PM2.5 levels also decreased significantly, with an average reduction of
4.31 units. Conversely, in counties where poverty increased, PM2.5
levels still decreased on average, but by a smaller margin of 2.81
units. This suggests that PM2.5 has generally declined across counties,
regardless of poverty trends, with a greater reduction observed in
counties experiencing poverty decreases.

\newpage

\section{Analysis}\label{analysis}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(yearly\_avg\_PM25 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Percent\_Below\_150\_Poverty }\SpecialCharTok{+}\NormalTok{ Minority\_Percentage, }\AttributeTok{data =}\NormalTok{ Merged\_2022)}
\FunctionTok{summary}\NormalTok{(model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = yearly_avg_PM25 ~ Percent_Below_150_Poverty + Minority_Percentage, 
##     data = Merged_2022)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.8246 -1.5909  0.2719  0.9759  5.2138 
## 
## Coefficients:
##                           Estimate Std. Error t value Pr(>|t|)   
## (Intercept)                3.51153    1.20821   2.906  0.00556 **
## Percent_Below_150_Poverty  0.10630    0.04495   2.365  0.02222 * 
## Minority_Percentage        0.03893    0.01521   2.560  0.01373 * 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 2.078 on 47 degrees of freedom
## Multiple R-squared:  0.2267, Adjusted R-squared:  0.1938 
## F-statistic:  6.89 on 2 and 47 DF,  p-value: 0.002377
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}

\CommentTok{\# Scatter Plot for Percent Below 150\% Poverty vs PM2.5}
\FunctionTok{ggplot}\NormalTok{(Merged\_2022, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Percent\_Below\_150\_Poverty, }\AttributeTok{y =}\NormalTok{ yearly\_avg\_PM25)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{color =} \StringTok{"darkblue"}\NormalTok{, }\AttributeTok{alpha =} \FloatTok{0.7}\NormalTok{, }\AttributeTok{size =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{color =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{se =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Relationship Between Poverty and PM2.5 (2022)"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Percent Below 150\% Poverty"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Yearly Average PM2.5 (μg/m³)"}\NormalTok{,}
    \AttributeTok{caption =} \StringTok{"Data Source: EPA and CDC"}
\NormalTok{  ) }\SpecialCharTok{+}
\NormalTok{  mytheme}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula = 'y ~ x'
\end{verbatim}

\includegraphics{Project_Template_files/figure-latex/unnamed-chunk-10-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Scatter Plot for Minority Percentage vs PM2.5}
\FunctionTok{ggplot}\NormalTok{(Merged\_2022, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Minority\_Percentage, }\AttributeTok{y =}\NormalTok{ yearly\_avg\_PM25)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{color =} \StringTok{"darkgreen"}\NormalTok{, }\AttributeTok{alpha =} \FloatTok{0.7}\NormalTok{, }\AttributeTok{size =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{color =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{se =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Relationship Between Minority Percentage and PM2.5 (2022)"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Minority Percentage"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Yearly Average PM2.5 (μg/m³)"}\NormalTok{,}
    \AttributeTok{caption =} \StringTok{"Data Source: EPA and CDC"}
\NormalTok{  ) }\SpecialCharTok{+}
\NormalTok{  mytheme}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula = 'y ~ x'
\end{verbatim}

\includegraphics{Project_Template_files/figure-latex/unnamed-chunk-10-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(yearly\_avg\_PM25 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Percent\_Below\_Poverty }\SpecialCharTok{+}\NormalTok{ Minority\_Percentage, }\AttributeTok{data =}\NormalTok{ Merged\_2000)}
\FunctionTok{summary}\NormalTok{(model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = yearly_avg_PM25 ~ Percent_Below_Poverty + Minority_Percentage, 
##     data = Merged_2000)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -9.2839 -2.8851  0.4562  2.6248  9.7625 
## 
## Coefficients:
##                       Estimate Std. Error t value Pr(>|t|)    
## (Intercept)            4.12689    2.12746   1.940   0.0587 .  
## Percent_Below_Poverty  0.05574    0.13247   0.421   0.6759    
## Minority_Percentage    0.17360    0.03403   5.102 6.55e-06 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 4.217 on 45 degrees of freedom
## Multiple R-squared:  0.3844, Adjusted R-squared:  0.3571 
## F-statistic: 14.05 on 2 and 45 DF,  p-value: 1.814e-05
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Scatter Plot for Percent Below Poverty vs PM2.5}
\FunctionTok{ggplot}\NormalTok{(Merged\_2000, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Percent\_Below\_Poverty, }\AttributeTok{y =}\NormalTok{ yearly\_avg\_PM25)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{color =} \StringTok{"darkblue"}\NormalTok{, }\AttributeTok{alpha =} \FloatTok{0.7}\NormalTok{, }\AttributeTok{size =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{color =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{se =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Relationship Between Poverty and PM2.5 (2000)"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Percent Below Poverty"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Yearly Average PM2.5 (μg/m³)"}\NormalTok{,}
    \AttributeTok{caption =} \StringTok{"Data Source: EPA and CDC"}
\NormalTok{  ) }\SpecialCharTok{+}
\NormalTok{  mytheme}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula = 'y ~ x'
\end{verbatim}

\includegraphics{Project_Template_files/figure-latex/unnamed-chunk-11-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Scatter Plot for Minority Percentage vs PM2.5}
\FunctionTok{ggplot}\NormalTok{(Merged\_2000, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Minority\_Percentage, }\AttributeTok{y =}\NormalTok{ yearly\_avg\_PM25)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{color =} \StringTok{"darkgreen"}\NormalTok{, }\AttributeTok{alpha =} \FloatTok{0.7}\NormalTok{, }\AttributeTok{size =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{color =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{se =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Relationship Between Minority Percentage and PM2.5 (2000)"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Minority Percentage"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Yearly Average PM2.5 (μg/m³)"}\NormalTok{,}
    \AttributeTok{caption =} \StringTok{"Data Source: EPA and CDC"}
\NormalTok{  ) }\SpecialCharTok{+}
\NormalTok{  mytheme}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula = 'y ~ x'
\end{verbatim}

\includegraphics{Project_Template_files/figure-latex/unnamed-chunk-11-2.pdf}

```

\subsection{Question 1: \textless insert specific question here and
ahttps://labs-az-00.oit.duke.edu:30106/graphics/plot\_zoom\_png?width=518\&height=363dd
additional subsections for additional questions below, if
needed\textgreater{}}\label{question-1-insert-specific-question-here-and-ahttpslabs-az-00.oit.duke.edu30106graphicsplot_zoom_pngwidth518height363dd-additional-subsections-for-additional-questions-below-if-needed}

\subsection{Question 2:}\label{question-2}

\newpage

\section{Summary and Conclusions}\label{summary-and-conclusions}

\newpage

\section{References}\label{references}

\textless add references here if relevant, otherwise delete this
section\textgreater{}

\end{document}
